### ISSUE TITLE
No case insensitive search filters for custom tags

### ISSUE THREAD

**Issue by 0xblackbird** [honoki/bbrf-dashboard#3]
Hi
I've noticed that when I store a domain or url along with a custom tag in bbrf, and use the bbrf.me dashboard, that I can only search and get the results with the exact match. I wish that there was an option to include case insensitive matches to the search filter.

Example:
Here I'm searching for the keyword **Portal**:
![image](https://user-images.githubusercontent.com/45142718/167503631-68d61682-580c-4f63-81de-23334ee09534.png)

While on this query, no results are returned:
![image1](https://user-images.githubusercontent.com/45142718/167503645-4a36b204-1101-4156-879f-2d8b28d24db7.png)

**Comment by honoki** [comment]
Hey @0xblackbird - thanks for the suggestion, it took me a while but filter is now case insensitive.

**Comment by 0xblackbird** [comment]
Hi! No worries at all, thank you for merging!

**Comment by 0xblackbird** [comment]
Hi! No worries at all, thank you for resolving this!
